// <auto-generated />
namespace Bullers.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class db_cr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_cr));
        
        string IMigrationMetadata.Id
        {
            get { return "202203261126374_db_cr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
